// ============================================================================
// All industry pricing data - import anywhere
// ============================================================================

export const PRICING_DATA = {
  hvac: {
    name: 'HVAC',
    hourlyRange: [75, 150],
    margin: [35, 50],
    services: {
      'Diagnostic': 89,
      'AC Tune-Up': 129,
      'Furnace Tune-Up': 129,
      'Filter Replacement': 49,
      'Thermostat Install': 175,
      'Capacitor Replace': 225,
      'Contactor Replace': 250,
      'Blower Motor': 450,
      'Compressor Repair': 650,
      'Refrigerant Recharge': 275,
      'Coil Cleaning': 195,
      'Duct Cleaning': 399,
      'Duct Repair': 350,
      'Mini Split Install': 3500,
      'Full System Install': 7500,
    },
  },
  plumbing: {
    name: 'Plumbing',
    hourlyRange: [75, 150],
    margin: [35, 50],
    services: {
      'Service Call': 99,
      'Drain Cleaning': 175,
      'Hydro Jetting': 450,
      'Toilet Repair': 150,
      'Toilet Replace': 350,
      'Faucet Repair': 125,
      'Faucet Replace': 225,
      'Garbage Disposal': 275,
      'Water Heater Flush': 150,
      'Water Heater Install': 1200,
      'Tankless WH Install': 2500,
      'Leak Repair': 250,
      'Pipe Repair': 350,
      'Sewer Camera': 275,
      'Sewer Line Repair': 2500,
      'Repipe (per fixture)': 450,
      'Sump Pump Install': 650,
    },
  },
  electrical: {
    name: 'Electrical',
    hourlyRange: [75, 150],
    margin: [35, 50],
    services: {
      'Service Call': 99,
      'Outlet Install': 150,
      'Outlet Repair': 100,
      'GFCI Outlet': 175,
      'USB Outlet': 200,
      'Switch Replace': 125,
      'Dimmer Install': 150,
      'Smart Switch': 200,
      'Ceiling Fan Install': 225,
      'Ceiling Fan Replace': 175,
      'Light Fixture': 175,
      'Recessed Light (each)': 200,
      'Under Cabinet Lights': 350,
      'Outdoor Lighting': 275,
      'Panel Inspection': 150,
      'Circuit Breaker': 200,
      'AFCI Breaker': 250,
      'Whole House Surge': 350,
      'Generator Hook-up': 750,
      'Panel Upgrade (100A)': 1800,
      'Panel Upgrade (200A)': 2500,
      'EV Charger Install': 800,
    },
  },
  cleaning: {
    name: 'Cleaning',
    hourlyRange: [35, 65],
    margin: [25, 40],
    services: {
      'Standard (under 1000sf)': 100,
      'Standard (1000-1500sf)': 135,
      'Standard (1500-2000sf)': 165,
      'Standard (2000-2500sf)': 195,
      'Standard (2500-3000sf)': 225,
      'Standard (3000+sf)': 275,
      'Deep Clean (under 1500sf)': 250,
      'Deep Clean (1500-2000sf)': 300,
      'Deep Clean (2000-2500sf)': 350,
      'Deep Clean (2500+sf)': 425,
      'Move-In/Out (under 1500sf)': 325,
      'Move-In/Out (1500-2000sf)': 400,
      'Move-In/Out (2000+sf)': 500,
      'Post-Construction': 500,
      'Office (per 1000sf)': 125,
      'Airbnb Turnover': 150,
      'Carpet Cleaning (per room)': 50,
      'Window Cleaning (add-on)': 75,
      'Fridge Cleaning': 45,
      'Oven Cleaning': 55,
      'Laundry (wash/fold)': 35,
    },
  },
  landscaping: {
    name: 'Landscaping',
    hourlyRange: [45, 85],
    margin: [25, 40],
    services: {
      'Mow (under 5000sf)': 40,
      'Mow (5000-10000sf)': 55,
      'Mow (10000-20000sf)': 75,
      'Mow (20000+sf)': 100,
      'Edging Only': 25,
      'Trim Only': 30,
      'Full Service (mow/edge/trim)': 65,
      'Leaf Cleanup (light)': 100,
      'Leaf Cleanup (heavy)': 175,
      'Mulch (per yard installed)': 85,
      'Rock/Gravel (per yard)': 95,
      'Bush/Hedge Trim': 150,
      'Tree Trim (small)': 200,
      'Tree Trim (medium)': 350,
      'Tree Removal (small)': 400,
      'Stump Grinding': 200,
      'Sod Install (per sqft)': 2,
      'Flower Bed Install': 300,
      'Sprinkler Repair': 125,
      'Sprinkler Head': 45,
      'Spring Cleanup': 275,
      'Fall Cleanup': 300,
      'Aeration': 125,
      'Overseeding': 150,
      'Fertilization': 75,
    },
  },
  painting: {
    name: 'Painting',
    hourlyRange: [40, 75],
    margin: [30, 45],
    services: {
      'Room - Small (10x10)': 275,
      'Room - Medium (12x12)': 350,
      'Room - Large (14x14)': 450,
      'Room - XL (16x16+)': 550,
      'Bathroom': 300,
      'Kitchen': 500,
      'Hallway': 200,
      'Stairway': 400,
      'Accent Wall': 175,
      'Ceiling (per room)': 150,
      'Trim/Baseboards (per room)': 125,
      'Door (each)': 75,
      'Interior Full (1000sf)': 1800,
      'Interior Full (1500sf)': 2500,
      'Interior Full (2000sf)': 3200,
      'Interior Full (2500sf)': 4000,
      'Exterior (1000sf)': 2500,
      'Exterior (1500sf)': 3500,
      'Exterior (2000sf)': 4500,
      'Exterior (2500sf)': 5500,
      'Deck Stain (small)': 350,
      'Deck Stain (large)': 600,
      'Fence (per linear ft)': 8,
      'Cabinet Refinish': 3000,
      'Popcorn Ceiling Removal': 3,
      'Wallpaper Removal (per room)': 300,
    },
  },
  pest: {
    name: 'Pest Control',
    hourlyRange: [50, 100],
    margin: [40, 55],
    services: {
      'Initial Treatment': 175,
      'Quarterly Service': 99,
      'Bi-Monthly Service': 85,
      'Monthly Service': 75,
      'One-Time Treatment': 199,
      'Ant Treatment': 175,
      'Roach Treatment': 200,
      'Spider Treatment': 150,
      'Wasp/Bee Removal': 175,
      'Rodent Control (setup)': 250,
      'Rodent Control (monthly)': 75,
      'Termite Inspection': 125,
      'Termite Treatment (house)': 1500,
      'Termite Bait System': 1200,
      'Bed Bug Treatment (room)': 350,
      'Bed Bug Treatment (house)': 1500,
      'Mosquito Treatment': 125,
      'Flea Treatment': 200,
      'Wildlife Removal': 350,
      'Exclusion Work': 500,
    },
  },
  roofing: {
    name: 'Roofing',
    hourlyRange: [50, 100],
    margin: [30, 45],
    services: {
      'Inspection': 150,
      'Emergency Tarp': 350,
      'Leak Repair (minor)': 350,
      'Leak Repair (major)': 600,
      'Shingle Repair (10 sqft)': 275,
      'Shingle Repair (25 sqft)': 450,
      'Flashing Repair': 350,
      'Vent Pipe Boot': 225,
      'Skylight Repair': 450,
      'Skylight Replace': 1200,
      'Gutter Clean': 175,
      'Gutter Repair': 275,
      'Gutter Install (per ft)': 12,
      'Gutter Guards (per ft)': 8,
      'Fascia Repair': 400,
      'Soffit Repair': 350,
      'Partial Reroof': 2500,
      'Full Reroof (per square)': 450,
      'Flat Roof Repair': 500,
      'Metal Roof Repair': 600,
    },
  },
  garage: {
    name: 'Garage Door',
    hourlyRange: [75, 125],
    margin: [35, 50],
    services: {
      'Service Call': 99,
      'Spring Replacement (1)': 225,
      'Spring Replacement (2)': 275,
      'Cable Repair': 175,
      'Cable Replace': 200,
      'Roller Replace (set)': 150,
      'Hinge Replace': 125,
      'Track Alignment': 125,
      'Track Replace': 275,
      'Opener Repair': 175,
      'Opener Install': 450,
      'Belt Drive Opener': 550,
      'Smart Opener': 650,
      'Keypad Install': 150,
      'Remote Program': 75,
      'Safety Sensor': 175,
      'Weather Seal': 125,
      'Panel Replace (single)': 350,
      'Full Door (single 8x7)': 1000,
      'Full Door (single 9x7)': 1100,
      'Full Door (double 16x7)': 1600,
      'Full Door (double 18x7)': 1800,
      'Insulated Door (add)': 300,
      'Windows (add)': 200,
    },
  },
  pressure: {
    name: 'Pressure Washing',
    hourlyRange: [50, 100],
    margin: [35, 50],
    services: {
      'Driveway (1 car)': 100,
      'Driveway (2 car)': 150,
      'Driveway (3 car)': 200,
      'Sidewalk (front)': 50,
      'Sidewalk (full)': 100,
      'Walkway': 75,
      'Patio (under 200sf)': 125,
      'Patio (200-400sf)': 175,
      'Patio (400+sf)': 250,
      'Deck (small)': 175,
      'Deck (medium)': 250,
      'Deck (large)': 350,
      'House Wash (1 story)': 275,
      'House Wash (2 story)': 400,
      'House Wash (3 story)': 550,
      'Fence (per 100 linear ft)': 150,
      'Roof Soft Wash': 450,
      'Gutter Brightening': 200,
      'Concrete Sealing': 200,
      'Full Property Bundle': 500,
    },
  },
  pool: {
    name: 'Pool Service',
    hourlyRange: [50, 90],
    margin: [30, 45],
    services: {
      'Weekly Service': 125,
      'Bi-Weekly Service': 150,
      'Monthly Service': 175,
      'One-Time Clean': 175,
      'Green to Clean (light)': 275,
      'Green to Clean (heavy)': 400,
      'Filter Clean (cartridge)': 125,
      'Filter Clean (DE)': 175,
      'Filter Clean (sand)': 150,
      'Pump Repair': 225,
      'Pump Replace': 600,
      'Motor Replace': 450,
      'Heater Repair': 275,
      'Heater Service': 175,
      'Salt Cell Replace': 450,
      'Salt Cell Clean': 125,
      'Valve Repair': 200,
      'Light Replace': 350,
      'Tile Cleaning': 250,
      'Acid Wash': 500,
      'Drain & Refill': 350,
      'Pool Opening': 225,
      'Pool Closing': 250,
      'Equipment Inspection': 125,
    },
  },
  window: {
    name: 'Window Cleaning',
    hourlyRange: [45, 75],
    margin: [30, 45],
    services: {
      'Interior (per window)': 8,
      'Exterior (per window)': 10,
      'In/Out (per window)': 15,
      'Interior Only (10 win)': 100,
      'Interior Only (20 win)': 175,
      'Interior Only (30 win)': 240,
      'Exterior Only (10 win)': 125,
      'Exterior Only (20 win)': 200,
      'Exterior Only (30 win)': 275,
      'In/Out (10 windows)': 175,
      'In/Out (20 windows)': 300,
      'In/Out (30 windows)': 400,
      'In/Out (40 windows)': 500,
      'French Doors (each)': 25,
      'Skylights (each)': 35,
      'Screen Cleaning (each)': 5,
      'Track Cleaning': 75,
      'Hard Water Removal (per win)': 15,
      'Construction Cleanup (per win)': 20,
      'Storefront (per pane)': 8,
      'High-Rise (per floor add)': 50,
    },
  },
} as const;

// Helper to get flat list of all prices
export function getAllPrices() {
  const prices: Array<{ industry: string; service: string; price: number }> = [];
  
  Object.entries(PRICING_DATA).forEach(([, data]) => {
    Object.entries(data.services).forEach(([service, price]) => {
      prices.push({
        industry: data.name,
        service,
        price,
      });
    });
  });
  
  return prices;
}

// Get price for specific service
export function getServicePrice(industry: string, service: string): number | null {
  const industryKey = Object.keys(PRICING_DATA).find(
    (k) => PRICING_DATA[k as keyof typeof PRICING_DATA].name.toLowerCase() === industry.toLowerCase()
  ) as keyof typeof PRICING_DATA | undefined;
  
  if (!industryKey) return null;
  
  const data = PRICING_DATA[industryKey];
  const serviceKey = Object.keys(data.services).find(
    (s) => s.toLowerCase().includes(service.toLowerCase())
  );
  
  if (!serviceKey) return null;
  
  return data.services[serviceKey as keyof typeof data.services];
}

// Get all services for industry
export function getIndustryServices(industry: string) {
  const industryKey = Object.keys(PRICING_DATA).find(
    (k) => PRICING_DATA[k as keyof typeof PRICING_DATA].name.toLowerCase() === industry.toLowerCase()
  ) as keyof typeof PRICING_DATA | undefined;
  
  if (!industryKey) return null;
  
  return PRICING_DATA[industryKey];
}

// Type exports
export type IndustryKey = keyof typeof PRICING_DATA;
export type Industry = typeof PRICING_DATA[IndustryKey];
