project_id = "vbmahppxoffjovtuflkh"

[functions.send-email]
verify_jwt = false

[functions.phone-numbers]
verify_jwt = true

[functions.send-sms]
verify_jwt = false

[functions.process-queue]
verify_jwt = false

[functions.sms-status-webhook]
verify_jwt = false

[functions.sms-webhook]
verify_jwt = false
