// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thbegonbonhswsbgszxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoYmVnb25ib25oc3dzYmdzenhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzNjIwMDcsImV4cCI6MjA4MzkzODAwN30.ZhBHFsfBWHtgQdoVTkpcKo0b_jaPuSUE1xGTODqwN6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});