"use client";

import { cn } from "@/lib/utils";
import "remixicon/fonts/remixicon.css";

// Comprehensive Remix Icon mapping
// Browse all icons: https://remixicon.com/
export const icons = {
  // Navigation & UI
  home: "ri-home-5-line",
  homeFill: "ri-home-5-fill",
  menu: "ri-menu-line",
  menuFill: "ri-menu-fill",
  menuDots: "ri-more-2-line",
  menuDotsVertical: "ri-more-2-fill",
  apps: "ri-apps-line",
  appsFill: "ri-apps-fill",
  appsAdd: "ri-apps-2-line",
  search: "ri-search-line",
  searchFill: "ri-search-fill",
  settings: "ri-settings-3-line",
  settingsFill: "ri-settings-3-fill",
  settingsSliders: "ri-equalizer-line",
  filter: "ri-filter-3-line",
  filterFill: "ri-filter-3-fill",
  sort: "ri-sort-desc",
  list: "ri-list-check",
  listCheck: "ri-list-check-2",
  browser: "ri-window-line",
  globe: "ri-global-line",
  globeFill: "ri-global-fill",
  world: "ri-earth-line",
  layers: "ri-stack-line",
  layersFill: "ri-stack-fill",
  dashboard: "ri-dashboard-line",
  dashboardFill: "ri-dashboard-fill",
  grid: "ri-grid-line",
  gridFill: "ri-grid-fill",
  sidebar: "ri-side-bar-line",
  layout: "ri-layout-grid-line",
  columns: "ri-layout-column-line",
  rows: "ri-layout-row-line",
  expand: "ri-fullscreen-line",
  compress: "ri-fullscreen-exit-line",
  maximize: "ri-maximize-line",
  minimize: "ri-minimize-line",
  
  // Arrows & Chevrons
  chevronLeft: "ri-arrow-left-s-line",
  chevronRight: "ri-arrow-right-s-line",
  chevronUp: "ri-arrow-up-s-line",
  chevronDown: "ri-arrow-down-s-line",
  chevronsLeft: "ri-arrow-left-double-line",
  chevronsRight: "ri-arrow-right-double-line",
  chevronsUp: "ri-arrow-up-double-line",
  chevronsDown: "ri-arrow-down-double-line",
  angleCircleRight: "ri-arrow-right-circle-line",
  arrowCircleRight: "ri-arrow-right-circle-line",
  arrowLeft: "ri-arrow-left-line",
  arrowRight: "ri-arrow-right-line",
  arrowUp: "ri-arrow-up-line",
  arrowDown: "ri-arrow-down-line",
  arrowUpRight: "ri-arrow-right-up-line",
  arrowDownLeft: "ri-arrow-left-down-line",
  undo: "ri-arrow-go-back-line",
  redo: "ri-arrow-go-forward-line",
  
  // Users & People
  user: "ri-user-line",
  userFill: "ri-user-fill",
  userAdd: "ri-user-add-line",
  userPlus: "ri-user-add-line",
  userMinus: "ri-user-minus-line",
  userCheck: "ri-user-follow-line",
  userX: "ri-user-unfollow-line",
  userCog: "ri-user-settings-line",
  users: "ri-group-line",
  usersFill: "ri-group-fill",
  usersAlt: "ri-team-line",
  userGroup: "ri-group-line",
  following: "ri-user-follow-line",
  portrait: "ri-user-3-line",
  
  // Communication
  phone: "ri-phone-line",
  phoneFill: "ri-phone-fill",
  phoneCall: "ri-phone-line",
  phoneIncoming: "ri-phone-line",
  phoneOutgoing: "ri-phone-line",
  phoneMissed: "ri-phone-line",
  phoneOff: "ri-phone-off-line",
  phoneCircle: "ri-phone-line",
  email: "ri-mail-line",
  emailFill: "ri-mail-fill",
  envelope: "ri-mail-line",
  envelopeOpen: "ri-mail-open-line",
  mail: "ri-mail-line",
  mailOpen: "ri-mail-open-line",
  inbox: "ri-inbox-line",
  inboxFill: "ri-inbox-fill",
  inboxIn: "ri-inbox-archive-line",
  inboxOut: "ri-inbox-unarchive-line",
  message: "ri-message-3-line",
  messageFill: "ri-message-3-fill",
  messageSquare: "ri-chat-1-line",
  messageAlt: "ri-chat-3-line",
  messageCircle: "ri-discuss-line",
  messages: "ri-message-2-line",
  comment: "ri-chat-1-line",
  comments: "ri-discuss-line",
  send: "ri-send-plane-line",
  sendFill: "ri-send-plane-fill",
  paperPlane: "ri-send-plane-line",
  megaphone: "ri-megaphone-line",
  bell: "ri-notification-3-line",
  bellFill: "ri-notification-3-fill",
  bellRing: "ri-notification-4-line",
  bellOff: "ri-notification-off-line",
  bellSlash: "ri-notification-off-line",
  headset: "ri-headphone-line",
  headphones: "ri-headphone-line",
  video: "ri-video-line",
  videoFill: "ri-video-fill",
  videoOff: "ri-video-off-line",
  mic: "ri-mic-line",
  micFill: "ri-mic-fill",
  micOff: "ri-mic-off-line",
  
  // Actions
  add: "ri-add-line",
  plus: "ri-add-line",
  plusSmall: "ri-add-line",
  plusCircle: "ri-add-circle-line",
  plusCircleFill: "ri-add-circle-fill",
  minus: "ri-subtract-line",
  minusCircle: "ri-indeterminate-circle-line",
  close: "ri-close-line",
  x: "ri-close-line",
  xCircle: "ri-close-circle-line",
  xCircleFill: "ri-close-circle-fill",
  closeSmall: "ri-close-line",
  closeCircle: "ri-close-circle-line",
  check: "ri-check-line",
  checkFill: "ri-check-fill",
  checkCircle: "ri-checkbox-circle-line",
  checkCircleFill: "ri-checkbox-circle-fill",
  checkbox: "ri-checkbox-line",
  edit: "ri-edit-line",
  editFill: "ri-edit-fill",
  edit2: "ri-edit-2-line",
  pencil: "ri-pencil-line",
  pen: "ri-pen-nib-line",
  trash: "ri-delete-bin-line",
  trashFill: "ri-delete-bin-fill",
  trash2: "ri-delete-bin-6-line",
  delete: "ri-delete-bin-line",
  refresh: "ri-refresh-line",
  refreshCw: "ri-refresh-line",
  rotateCw: "ri-rotate-lock-line",
  rotateCcw: "ri-anticlockwise-line",
  download: "ri-download-line",
  downloadFill: "ri-download-fill",
  upload: "ri-upload-line",
  uploadFill: "ri-upload-fill",
  share: "ri-share-line",
  shareFill: "ri-share-fill",
  share2: "ri-share-forward-line",
  externalLink: "ri-external-link-line",
  copy: "ri-file-copy-line",
  copyFill: "ri-file-copy-fill",
  clipboard: "ri-clipboard-line",
  clipboardFill: "ri-clipboard-fill",
  clipboardCheck: "ri-task-line",
  clipboardList: "ri-survey-line",
  link: "ri-link",
  link2: "ri-links-line",
  unlink: "ri-link-unlink",
  more: "ri-more-line",
  moreHorizontal: "ri-more-line",
  moreVertical: "ri-more-2-line",
  ellipsis: "ri-more-line",
  grip: "ri-drag-move-2-line",
  gripVertical: "ri-draggable",
  move: "ri-drag-move-line",
  drag: "ri-draggable",
  
  // Media & Files
  play: "ri-play-line",
  playFill: "ri-play-fill",
  playCircle: "ri-play-circle-line",
  pause: "ri-pause-line",
  pauseFill: "ri-pause-fill",
  stop: "ri-stop-line",
  stopFill: "ri-stop-fill",
  skipBack: "ri-skip-back-line",
  skipForward: "ri-skip-forward-line",
  rewind: "ri-rewind-line",
  fastForward: "ri-speed-line",
  volume: "ri-volume-up-line",
  volume1: "ri-volume-down-line",
  volume2: "ri-volume-up-line",
  volumeX: "ri-volume-mute-line",
  volumeMute: "ri-volume-mute-line",
  camera: "ri-camera-line",
  cameraFill: "ri-camera-fill",
  cameraOff: "ri-camera-off-line",
  image: "ri-image-line",
  imageFill: "ri-image-fill",
  images: "ri-gallery-line",
  picture: "ri-image-line",
  music: "ri-music-line",
  musicFill: "ri-music-fill",
  film: "ri-film-line",
  
  // Files & Documents
  file: "ri-file-line",
  fileFill: "ri-file-fill",
  fileText: "ri-file-text-line",
  fileAdd: "ri-file-add-line",
  filePlus: "ri-file-add-line",
  fileMinus: "ri-file-reduce-line",
  fileCheck: "ri-file-check-line",
  fileX: "ri-file-forbid-line",
  fileEdit: "ri-file-edit-line",
  fileSearch: "ri-file-search-line",
  document: "ri-article-line",
  documentSigned: "ri-draft-line",
  folder: "ri-folder-line",
  folderFill: "ri-folder-fill",
  folderOpen: "ri-folder-open-line",
  folderAdd: "ri-folder-add-line",
  folderPlus: "ri-folder-add-line",
  folderMinus: "ri-folder-reduce-line",
  archive: "ri-archive-line",
  archiveFill: "ri-archive-fill",
  
  // Social & Feedback
  heart: "ri-heart-line",
  heartFilled: "ri-heart-fill",
  heartOff: "ri-dislike-line",
  star: "ri-star-line",
  starFilled: "ri-star-fill",
  starHalf: "ri-star-half-line",
  bookmark: "ri-bookmark-line",
  bookmarkFilled: "ri-bookmark-fill",
  flag: "ri-flag-line",
  flagFill: "ri-flag-fill",
  thumbsUp: "ri-thumb-up-line",
  thumbsUpFill: "ri-thumb-up-fill",
  thumbsDown: "ri-thumb-down-line",
  smile: "ri-emotion-happy-line",
  frown: "ri-emotion-unhappy-line",
  meh: "ri-emotion-normal-line",
  laugh: "ri-emotion-laugh-line",
  angry: "ri-emotion-unhappy-line",
  
  // E-commerce & Business
  cart: "ri-shopping-cart-line",
  cartFill: "ri-shopping-cart-fill",
  shoppingCart: "ri-shopping-cart-line",
  cartAdd: "ri-shopping-cart-2-line",
  cartPlus: "ri-shopping-cart-2-line",
  bag: "ri-shopping-bag-line",
  bagFill: "ri-shopping-bag-fill",
  shoppingBag: "ri-shopping-bag-line",
  creditCard: "ri-bank-card-line",
  creditCardFill: "ri-bank-card-fill",
  wallet: "ri-wallet-line",
  walletFill: "ri-wallet-fill",
  dollar: "ri-money-dollar-circle-line",
  dollarSign: "ri-money-dollar-circle-line",
  usd: "ri-money-dollar-circle-fill",
  euro: "ri-money-euro-circle-line",
  coins: "ri-coins-line",
  coin: "ri-coin-line",
  moneyBag: "ri-hand-coin-line",
  piggyBank: "ri-funds-line",
  bank: "ri-bank-line",
  bankFill: "ri-bank-fill",
  briefcase: "ri-briefcase-line",
  briefcaseFill: "ri-briefcase-fill",
  receipt: "ri-receipt-line",
  receiptFill: "ri-receipt-fill",
  scale: "ri-scales-line",
  balance: "ri-scales-line",
  invoice: "ri-bill-line",
  quote: "ri-file-list-3-line",
  fileInvoice: "ri-bill-line",
  barcode: "ri-barcode-line",
  qrCode: "ri-qr-code-line",
  tag: "ri-price-tag-3-line",
  tagFill: "ri-price-tag-3-fill",
  tags: "ri-price-tag-2-line",
  percent: "ri-percent-line",
  percentage: "ri-percent-line",
  
  // Time & Calendar
  clock: "ri-time-line",
  clockFill: "ri-time-fill",
  watch: "ri-timer-line",
  timer: "ri-timer-2-line",
  stopwatch: "ri-timer-flash-line",
  hourglass: "ri-hourglass-line",
  alarm: "ri-alarm-line",
  alarmClock: "ri-alarm-line",
  calendar: "ri-calendar-line",
  calendarFill: "ri-calendar-fill",
  calendarDays: "ri-calendar-2-line",
  calendarClock: "ri-calendar-schedule-line",
  calendarLines: "ri-calendar-todo-line",
  calendarPlus: "ri-calendar-check-line",
  calendarMinus: "ri-calendar-close-line",
  calendarCheck: "ri-calendar-check-line",
  calendarX: "ri-calendar-close-line",
  history: "ri-history-line",
  
  // Location & Maps
  mapPin: "ri-map-pin-line",
  mapPinFill: "ri-map-pin-fill",
  pin: "ri-pushpin-line",
  marker: "ri-map-pin-line",
  map: "ri-map-line",
  mapFill: "ri-map-fill",
  mapMarker: "ri-map-pin-2-line",
  compass: "ri-compass-line",
  compassFill: "ri-compass-fill",
  navigation: "ri-navigation-line",
  globe2: "ri-earth-line",
  
  // Security & Privacy
  lock: "ri-lock-line",
  lockFill: "ri-lock-fill",
  lockOpen: "ri-lock-unlock-line",
  unlock: "ri-lock-unlock-line",
  key: "ri-key-line",
  keyFill: "ri-key-fill",
  keyhole: "ri-key-2-line",
  shield: "ri-shield-line",
  shieldFill: "ri-shield-fill",
  shieldCheck: "ri-shield-check-line",
  shieldOff: "ri-shield-cross-line",
  verified: "ri-verified-badge-line",
  verifiedFill: "ri-verified-badge-fill",
  badge: "ri-medal-line",
  badgeCheck: "ri-award-line",
  eye: "ri-eye-line",
  eyeFill: "ri-eye-fill",
  eyeOff: "ri-eye-off-line",
  eyeSlash: "ri-eye-off-line",
  fingerprint: "ri-fingerprint-line",
  scan: "ri-scan-line",
  
  // Info & Status
  info: "ri-information-line",
  infoFill: "ri-information-fill",
  infoCircle: "ri-information-line",
  question: "ri-question-line",
  questionFill: "ri-question-fill",
  questionCircle: "ri-question-line",
  help: "ri-question-line",
  helpCircle: "ri-questionnaire-line",
  alertCircle: "ri-error-warning-line",
  alertCircleFill: "ri-error-warning-fill",
  alertTriangle: "ri-alert-line",
  alertTriangleFill: "ri-alert-fill",
  warning: "ri-error-warning-line",
  exclamation: "ri-error-warning-line",
  error: "ri-close-circle-line",
  errorFill: "ri-close-circle-fill",
  xMark: "ri-close-circle-line",
  success: "ri-checkbox-circle-line",
  successFill: "ri-checkbox-circle-fill",
  checkMark: "ri-checkbox-circle-line",
  ban: "ri-forbid-line",
  slash: "ri-forbid-2-line",
  
  // Charts & Analytics
  chart: "ri-bar-chart-line",
  chartFill: "ri-bar-chart-fill",
  chartBar: "ri-bar-chart-2-line",
  chartLine: "ri-line-chart-line",
  chartPie: "ri-pie-chart-line",
  chartPieFill: "ri-pie-chart-fill",
  chartArea: "ri-bar-chart-grouped-line",
  chartHistogram: "ri-bar-chart-horizontal-line",
  stats: "ri-bar-chart-box-line",
  activity: "ri-pulse-line",
  pulse: "ri-pulse-line",
  trendUp: "ri-arrow-up-line",
  trendingUp: "ri-arrow-right-up-line",
  trendDown: "ri-arrow-down-line",
  trendingDown: "ri-arrow-right-down-line",
  target: "ri-focus-3-line",
  crosshair: "ri-crosshair-line",
  crosshairs: "ri-crosshair-2-line",
  gauge: "ri-dashboard-3-line",
  
  // Tech & Development
  code: "ri-code-line",
  codeFill: "ri-code-fill",
  codeSimple: "ri-code-s-line",
  codeBranch: "ri-git-branch-line",
  codeMerge: "ri-git-merge-line",
  terminal: "ri-terminal-line",
  terminalFill: "ri-terminal-fill",
  command: "ri-command-line",
  database: "ri-database-line",
  databaseFill: "ri-database-fill",
  server: "ri-server-line",
  serverFill: "ri-server-fill",
  cloud: "ri-cloud-line",
  cloudFill: "ri-cloud-fill",
  cloudUpload: "ri-upload-cloud-line",
  cloudDownload: "ri-download-cloud-line",
  wifi: "ri-wifi-line",
  wifiOff: "ri-wifi-off-line",
  bluetooth: "ri-bluetooth-line",
  cpu: "ri-cpu-line",
  chip: "ri-cpu-line",
  microchip: "ri-cpu-line",
  monitor: "ri-computer-line",
  laptop: "ri-macbook-line",
  smartphone: "ri-smartphone-line",
  tablet: "ri-tablet-line",
  mouse: "ri-mouse-line",
  keyboard: "ri-keyboard-line",
  
  // Misc Objects
  lightbulb: "ri-lightbulb-line",
  lightbulbFill: "ri-lightbulb-fill",
  bulb: "ri-lightbulb-line",
  bolt: "ri-flashlight-line",
  lightning: "ri-flashlight-line",
  zap: "ri-flashlight-line",
  flash: "ri-flashlight-line",
  magic: "ri-magic-line",
  magicFill: "ri-magic-fill",
  wand: "ri-magic-line",
  wandSparkles: "ri-magic-line",
  wandMagic: "ri-magic-line",
  bahai: "ri-star-line",
  sparkle: "ri-sparkling-line",
  sparkles: "ri-sparkling-2-line",
  sparklesFill: "ri-sparkling-2-fill",
  stars: "ri-sparkling-line",
  crown: "ri-vip-crown-line",
  crownFill: "ri-vip-crown-fill",
  trophy: "ri-trophy-line",
  trophyFill: "ri-trophy-fill",
  award: "ri-award-line",
  awardFill: "ri-award-fill",
  medal: "ri-medal-line",
  graduationCap: "ri-graduation-cap-line",
  school: "ri-school-line",
  book: "ri-book-line",
  bookFill: "ri-book-fill",
  bookOpen: "ri-book-open-line",
  bookmark2: "ri-bookmark-line",
  paw: "ri-bear-smile-line",
  rocket: "ri-rocket-line",
  rocketFill: "ri-rocket-fill",
  plane: "ri-plane-line",
  car: "ri-car-line",
  truck: "ri-truck-line",
  bicycle: "ri-riding-line",
  gift: "ri-gift-line",
  giftFill: "ri-gift-fill",
  present: "ri-gift-line",
  box: "ri-box-3-line",
  package: "ri-box-3-line",
  fire: "ri-fire-line",
  fireFill: "ri-fire-fill",
  flame: "ri-fire-line",
  sun: "ri-sun-line",
  sunFill: "ri-sun-fill",
  moon: "ri-moon-line",
  moonFill: "ri-moon-fill",
  cloudSun: "ri-sun-cloudy-line",
  rainbow: "ri-rainbow-line",
  umbrella: "ri-umbrella-line",
  snowflake: "ri-snowy-line",
  thermometer: "ri-temp-hot-line",
  droplet: "ri-drop-line",
  water: "ri-water-flash-line",
  waves: "ri-water-flash-line",
  leaf: "ri-leaf-line",
  tree: "ri-plant-line",
  flower: "ri-flower-line",
  bug: "ri-bug-line",
  hammer: "ri-hammer-line",
  wrench: "ri-tools-line",
  tools: "ri-tools-line",
  screwdriver: "ri-tools-line",
  paintBrush: "ri-brush-line",
  
  // Buildings & Places
  home2: "ri-home-line",
  house: "ri-home-4-line",
  houseFill: "ri-home-4-fill",
  building: "ri-building-line",
  buildingFill: "ri-building-fill",
  office: "ri-building-2-line",
  store: "ri-store-line",
  storeFill: "ri-store-fill",
  shop: "ri-store-2-line",
  hospital: "ri-hospital-line",
  factory: "ri-building-4-line",
  warehouse: "ri-community-line",
  
  // Integrations & Connections
  plug: "ri-plug-line",
  unplug: "ri-plug-2-line",
  puzzle: "ri-puzzle-line",
  puzzlePiece: "ri-puzzle-line",
  api: "ri-code-box-line",
  rss: "ri-rss-line",
  webhook: "ri-link-m",
  network: "ri-share-circle-line",
  networkCloud: "ri-cloud-line",
  
  // Sequences & Automation
  sequence: "ri-git-commit-line",
  repeat: "ri-repeat-line",
  repeat1: "ri-repeat-one-line",
  arrowsRepeat: "ri-repeat-line",
  arrowsRepeat1: "ri-repeat-one-line",
  shuffle: "ri-shuffle-line",
  automation: "ri-robot-line",
  workflow: "ri-flow-chart",
  process: "ri-flow-chart",
  gitBranch: "ri-git-branch-line",
  gitMerge: "ri-git-merge-line",
  split: "ri-git-branch-line",
  merge: "ri-git-merge-line",
  
  // Campaigns & Marketing
  campaign: "ri-megaphone-line",
  broadcast: "ri-broadcast-line",
  broadcastTower: "ri-base-station-line",
  antenna: "ri-base-station-line",
  satellite: "ri-signal-tower-line",
  signal: "ri-signal-wifi-line",
  signalAlt: "ri-signal-wifi-3-line",
  
  // Retention & Loyalty
  retention: "ri-refresh-line",
  loyalty: "ri-hearts-line",
  handshake: "ri-hand-heart-line",
  handHoldingHeart: "ri-hand-heart-line",
  
  // AI & Intelligence
  ai: "ri-brain-line",
  aiFill: "ri-brain-fill",
  brain: "ri-brain-line",
  robot: "ri-robot-line",
  robotFill: "ri-robot-fill",
  headSideBrain: "ri-brain-line",
  cpu2: "ri-cpu-line",
  
  // Loading & Progress
  spinner: "ri-loader-4-line",
  loading: "ri-loader-line",
  loader: "ri-loader-4-line",
  loader2: "ri-loader-5-line",
  
  // Auth & Account
  logout: "ri-logout-box-line",
  logOut: "ri-logout-box-r-line",
  signOut: "ri-logout-box-r-line",
  signOutAlt: "ri-logout-box-r-line",
  login: "ri-login-box-line",
  logIn: "ri-login-box-line",
  signIn: "ri-login-box-line",
  signInAlt: "ri-login-box-line",
  power: "ri-shut-down-line",
  powerOff: "ri-shut-down-line",
  
  // Misc UI
  palette: "ri-palette-line",
  paintbrush: "ri-brush-line",
  brush: "ri-brush-line",
  eraser: "ri-eraser-line",
  scissors: "ri-scissors-line",
  crop: "ri-crop-line",
  ruler: "ri-ruler-line",
  rulerCombined: "ri-ruler-2-line",
  print: "ri-printer-line",
  printer: "ri-printer-line",
  save: "ri-save-line",
  saveFill: "ri-save-fill",
  disk: "ri-save-line",
  at: "ri-at-line",
  hash: "ri-hashtag",
  hashtag: "ri-hashtag",
  asterisk: "ri-asterisk",
  circle: "ri-checkbox-blank-circle-line",
  circleFill: "ri-checkbox-blank-circle-fill",
  square: "ri-checkbox-blank-line",
  squareFill: "ri-checkbox-blank-fill",
  triangle: "ri-triangle-line",
  octagon: "ri-octagon-line",
  hexagon: "ri-hexagon-line",
  
  // Text & Typography
  bold: "ri-bold",
  italic: "ri-italic",
  underline: "ri-underline",
  strikethrough: "ri-strikethrough",
  alignLeft: "ri-align-left",
  alignCenter: "ri-align-center",
  alignRight: "ri-align-right",
  alignJustify: "ri-align-justify",
  listUl: "ri-list-unordered",
  listOl: "ri-list-ordered",
  indent: "ri-indent-increase",
  outdent: "ri-indent-decrease",
  quote2: "ri-double-quotes-r",
  quoteRight: "ri-double-quotes-r",
  heading: "ri-heading",
  paragraph: "ri-paragraph",
  textSize: "ri-font-size",
  font: "ri-font-size-2",
  type: "ri-text",
  text: "ri-text",
  
  // Math & Numbers
  calculator: "ri-calculator-line",
  plusMinus: "ri-add-line",
  divide: "ri-divide-line",
  equal: "ri-equal-line",
  notEqual: "ri-subtract-line",
  greaterThan: "ri-arrow-right-line",
  lessThan: "ri-arrow-left-line",
  infinity: "ri-infinity-line",
  
  // Arrows special
  arrowLeftRight: "ri-arrow-left-right-line",
  arrowUpDown: "ri-arrow-up-down-line",
  arrowsAlt: "ri-fullscreen-line",
  arrowsAltH: "ri-arrow-left-right-line",
  arrowsAltV: "ri-arrow-up-down-line",
  maximize2: "ri-fullscreen-line",
  minimize2: "ri-fullscreen-exit-line",
  arrowsMaximize: "ri-fullscreen-line",
  arrowsMinimize: "ri-fullscreen-exit-line",
  arrows: "ri-drag-move-2-line",
  
  // Cleaning specific icons
  sprayCan: "ri-ink-bottle-line",
  hardHat: "ri-user-star-line",
  chair: "ri-armchair-line",
  bedDouble: "ri-hotel-bed-line",
  utensils: "ri-restaurant-line",
  iron: "ri-shirt-line",
  dog: "ri-bear-smile-line",
  boxes: "ri-archive-stack-line",
  
  // Social Media
  twitter: "ri-twitter-x-line",
  facebook: "ri-facebook-line",
  instagram: "ri-instagram-line",
  linkedin: "ri-linkedin-line",
  youtube: "ri-youtube-line",
  github: "ri-github-line",
  google: "ri-google-line",
  
} as const;

export type IconName = keyof typeof icons;

interface IconProps {
  name: IconName;
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | "4xl";
  className?: string;
  filled?: boolean;
  style?: React.CSSProperties;
}

// Size classes with explicit width/height for proper centering
const sizeClasses = {
  xs: "text-[12px]",
  sm: "text-[14px]",
  md: "text-[16px]",
  lg: "text-[18px]",
  xl: "text-[20px]",
  "2xl": "text-[24px]",
  "3xl": "text-[30px]",
  "4xl": "text-[36px]",
};

export function Icon({ name, size = "md", className, filled = false, style }: IconProps) {
  let iconClass = icons[name];
  
  if (!iconClass) {
    console.warn(`Icon "${name}" not found`);
    return null;
  }
  
  // If filled version requested, try to use fill variant
  if (filled) {
    const filledName = `${name}Fill` as IconName;
    if (icons[filledName]) {
      iconClass = icons[filledName];
    } else {
      // Try converting line to fill
      iconClass = iconClass.replace("-line", "-fill") as typeof iconClass;
    }
  }
  
  return (
    <i 
      className={cn(
        iconClass,
        sizeClasses[size],
        "inline-flex items-center justify-center leading-none shrink-0",
        className
      )}
      style={style}
    />
  );
}

// Export for type checking
export { icons as iconNames };
